### ISSUE TITLE
App Updates

### ISSUE THREAD

**Issue by cptnhadd0ck** [lingeringwillx/How-to-Dumbify-Your-Android-Smartphone#1]
Hey,
great comprehensive guide you have there. I have been wanting to to the same thing for a while now. My only concern is the missing app updates. How do you handle it? Do you sideload new apks from your computer? 

Currently I'm still using an iPhone, because through parental controls I can hide appstore and browser with a passcode I don't know, while automatic app updates are activated. Have been wanting to switch to Android (GrapheneOS) for a while, only this issue is holding me back.

I'm not a frequent Github user, so sorry if this is the wrong place to ask.

best regards
haddock

**Comment by lingeringwillx** [comment]
Hello..

I download the Aurora Store every now and then and update the apps from there. If you're using LineageOS with MicroG then you'd have to blacklist Google Play Services in the app to prevent it from getting updated.

I have not tried GrapheneOS but it might be possible to do something similar to this guide with that rom.

**Comment by skbnoqtrjf** [comment]
> Hey, great comprehensive guide you have there. I have been wanting to to the same thing for a while now. My only concern is the missing app updates. How do you handle it? Do you sideload new apks from your computer?
> 
> Currently I'm still using an iPhone, because through parental controls I can hide appstore and browser with a passcode I don't know, while automatic app updates are activated. Have been wanting to switch to Android (GrapheneOS) for a while, only this issue is holding me back.
> 
> I'm not a frequent Github user, so sorry if this is the wrong place to ask.
> 
> best regards haddock

sorry before I also considered using Iphone screen time but it can easily bypass, sadly

**Comment by theycallmesmule** [comment]
> Hello..
> 
> I download the Aurora Store every now and then and update the apps from there. If you're using LineageOS with MicroG then you'd have to blacklist Google Play Services in the app to prevent it from getting updated.
> 
> I have not tried GrapheneOS but it might be possible to do something similar to this guide with that rom.

What exactly do you mean by "blacklist google play services?"
I thought it was removed from the phone.

Super interested in doing this to my phone

**Comment by lingeringwillx** [comment]
> > Hello..
> > I download the Aurora Store every now and then and update the apps from there. If you're using LineageOS with MicroG then you'd have to blacklist Google Play Services in the app to prevent it from getting updated.
> > I have not tried GrapheneOS but it might be possible to do something similar to this guide with that rom.
> 
> What exactly do you mean by "blacklist google play services?" I thought it was removed from the phone.
> 
> Super interested in doing this to my phone

In the MicroG version of LineageOS, this is a part MicroG's implementation of Google APIs rather than the actual Google Play Services (It pretends to be GPS).

It's not supposed to updated because that would cause it to be replaced with GPS.

The Aurora Store has a blacklist option, so that the GPS app won't get updated along with other apps.
