### ISSUE TITLE
A risk: OTA update?

### ISSUE THREAD

**Issue by skbnoqtrjf** [lingeringwillx/How-to-Dumbify-Your-Android-Smartphone#3]
Hello, do the removed apps reinstall after a system OTA update?

**Comment by lingeringwillx** [comment]
Yes, you'd have to remove the apps again after an update.

**Comment by skbnoqtrjf** [comment]
> Yes, you'd have to remove the apps again after an update.

this is really bad news for me. I think I should delete the "Updater" app, too, this package I think: _package:/system_ext/priv-app/Updater/Updater.apk=org.lineageos.updater_, I will update the OS manually based on my interest. Do you think it is safe to do it?

**Comment by lingeringwillx** [comment]
> > Yes, you'd have to remove the apps again after an update.
> 
> this is really bad news for me. I think I should delete the "Updater" app, too, this package I think: _package:/system_ext/priv-app/Updater/Updater.apk=org.lineageos.updater_, I will update the OS manually based on my interest. Do you think it is safe to do it?

I don't know, deleting certain apps could break the rom. Only way to know is to try.

**Comment by skbnoqtrjf** [comment]
> > > Yes, you'd have to remove the apps again after an update.
> > 
> > 
> > this is really bad news for me. I think I should delete the "Updater" app, too, this package I think: _package:/system_ext/priv-app/Updater/Updater.apk=org.lineageos.updater_, I will update the OS manually based on my interest. Do you think it is safe to do it?
> 
> I don't know, deleting certain apps could break the rom. Only way to know is to try.

yes, no problem, if something failed, I can fix it by reinstalling the OS. But this is only way for me. haha

**Comment by skbnoqtrjf** [comment]
@lingeringwillx Hello, do you know how to skip a system app update package (I mean only one app, for example "Browser/Jelly") while updating via OTA? Is there any way to modify some update scripts via ADB to perform this?

**Comment by lingeringwillx** [comment]
No I'm not aware of a way to do that.

**Comment by skbnoqtrjf** [comment]
@lingeringwillx I already removed "package:/system_ext/priv-app/Updater/Updater.apk=org.lineageos.updater", it is fine, it is only removed inside the Setting -> System like a normal app, not affect other apps inside Setting. But I don't know if the system can update OTA itself without the "Updater" app. I am waiting for the next LineageOS build for my phone to confirm...
