### ISSUE TITLE
You don't need to install LineageOS for MicroG anymore... instead just install official LineageOS

### ISSUE THREAD

**Issue by skbnoqtrjf** [lingeringwillx/How-to-Dumbify-Your-Android-Smartphone#6]
Actually, you don't need to install LineageOS for MicroG because now LineageOS has already supported MicroG officially inside their builds, the detailed info is here: https://www.reddit.com/r/LineageOS/comments/1b11zex/los_has_added_internal_microg_support/, so all you need is to flash LineageOS and then install 3 MicroG APKs, find them here: https://microg.org/download.html. So, you don't need to remove the F-droid app store because it's not preinstalled in LineageOS.

**Comment by lingeringwillx** [comment]
New version of the guide works without MicroG.
